### ISSUE TITLE
Packaging Questions

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#23]
1. What is the win-ia32-unpacked folder?

2. What is the win-unpacked folder?

3. What is the TheProtonApp-0.0.1-ia32-win.zip (47MB) file?

4. What is the TheProtonApp-0.0.1-win.zip (57MB)  file? 

![package-app](https://cloud.githubusercontent.com/assets/19224635/22829240/eaa68740-efa1-11e6-8a2b-1fd6103a3802.png)

**Comment by luismanuel001** [comment]
This are the standard output files of electron-builder (official recommended way to package applications):

1) Extracted TheProtonApp-0.0.1-ia32-win.zip
2) Extracted TheProtonApp-0.0.1-win.zip
3) This is the Packaged application for Windows 32 bits
4) This is the Packaged application for Windows 64 bits

The "0.0.1" in the zip filenames refer to the application version defined on the package.json file.

I can add a gulp clean up step to delete the *-unpacked directories after the zip files are generated, and rename the zip files to something else, but I left the defaults since I didn't find a specific filename patten on the requirements.

**Comment by distributev** [comment]
Out of the box which is the most portable zip file?

If I take the TheProtonApp-0.0.1-ia32-win.zip this file will work (out of the box) on both the older Windows 32 bits machines and with the latest / most recent Windows 64 bits

**Comment by luismanuel001** [comment]
Correct,  TheProtonApp-0.0.1-ia32-win.zip will work for both 32 and 64 bit Windows platforms

**Comment by distributev** [comment]
OK.

Yes I would like the release folder to be clean and to contain only the output zip files which I am interested.
