### ISSUE TITLE
020 - Implementation of Cloud Email Service Providers does not reflect the requirements

### ISSUE THREAD

**Issue by distributev** [distributev/the-proton#6]
Make it look like the requirements.

![issue05](https://cloud.githubusercontent.com/assets/19224635/22499697/942c8f24-e860-11e6-9ae5-7d7b0ec31b4f.png)

**Comment by distributev** [comment]
How was this fixed? I don't see any change in the GUI.

Please see the above screen-shot - the implementation is still not done as in the left part of the screen-shot.

**Comment by luismanuel001** [comment]
Did you pull the latest changes?

Are we looking at the same screen, Configuration > Email > Connection Settings? 

This is what it looks like on my machine:
![screen shot 2017-02-02 at 2 13 10 pm](https://cloud.githubusercontent.com/assets/847539/22562184/dd2ce33a-e951-11e6-8c31-2b5141f17897.png)

The only different thing I see, is that the buttons are white (bootstrap btn-default colors, so it looks consistent through all the app) instead of gray, and that they don't all fit on one row (because I don't think there is enough room, since on the original apps screenshot there are only 4 buttons and on the new one there are 5)

**Comment by distributev** [comment]
The layout (not the colors) should be the same as in the left (screen-shot at the top of this thread). 

Following are the differences I notice now.

1. On the left I see Microsoft Exchange Server text and logo <-> on the right it's Office 365
2. On the left I see 4 buttons Office365, Google Apps, Mandrill and SendGrid just on a single row <-> on the right I see 5 buttons on 2 rows 
3. All 4 buttons should align on a single row.

The layout should be the same.

Make sure the 4 buttons will have the same single row layout otherwise if they will not have enough space and they will fall on 2nd line it might be a hint that its because of the same root cause (screen size too small) like https://github.com/distributev/the-proton/issues/9

**Comment by luismanuel001** [comment]
ok, I just thought this list should be the same as the one on the Email cloud providers view.

On this view, it isn't very clear what the functionality of that section is, so I made some assumptions.

1) What should the cloud providers do? I assumed they will change the "selected" provider, so in the current implementation, when you click on a button, it changes the cloud provider description above it. Please verify this is the desired functionality, or correct me if I'm wrong.

2) If the above is true, since you want me to remove the microsoft exchange button, how should a user go back to select exchange when they have clicked on another provider's button?

I just pushed some layout fixes, so please pull the latest changes and test before answering.

**Comment by distributev** [comment]
**For fixing this just make this portion of the GUI to 100% match the mentioned screen-shot ==> If you do this we will be fine.** 

Some more background information

This part of the GUI is just promotional "read-only" info so that users can see that the "good old" Microsoft Exchange is easily supported out of the box but if they want (or need) a  more "modern" alternative to MS Exchange then we have few good cloud options which we endorse as being "good" (and we endorse these cloud options without trying too hard to push people away from MS Exchange - users are somehow in love with their Exchange and just trying to move them away and you get "resistance" and "concerns" like where is MS Exchange? you don't support MS Exchange?) 

1. Most of the users are stuck with the "good old" Microsoft Exchange because this is what their company uses ==> these users have the Connection settings screen to enter their Exchange SMTP login details.

2. However, if they want (or have a real need), the cloud options are available too. And we make the task of starting with cloud vendors very easy for users. Each cloud option "Well known service" have it's own SMTP settings (different port and other things for which each cloud has its own documentation) ==> In order to make things easier for people we offer the Well Known Services button ==> which people can use to "load" the default "well-known" settings for their our cloud option ==> For each of the mentioned "well known services" our software will help the users by pre-populating the SMTP configuration settings which are specific for that vendor (i.e. port for instance) ==> users will only need to provide their user/password (the rest of the configuration we will pre-populate using "Well Known Services")

**For fixing this just make this portion of the GUI to 100% match the mentioned screen-shot ==> If you do this we will be fine.**

**Comment by luismanuel001** [comment]
ok, so did you have time to check? I think the current implementation matches the original screenshot very closely.

**Comment by distributev** [comment]
Yes it's not exact but it's fine.
